package:
    name: tryingsnake
    version: "0.2.6"

requirements:
    build:
      - setuptools
      - python

    run:
      - python

test:
    requires:
      - nose
    imports:
      - tryingsnake
    commands:
      - nosetests --with-doctest --doctest-extension rst

about:
    home: https://github.com/zero323/tryingsnake/
    license: MIT
